version: 0.2

phases:
  pre_build:
    commands:
      # Login to AWS
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 564667093156.dkr.ecr.us-east-2.amazonaws.com
      # Add environment
      - REPOSITORY_URI=564667093156.dkr.ecr.us-east-2.amazonaws.com/test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest-codebuild}
  build:
    commands:
    # Build docker image 
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG ./App
  post_build:
    commands:
      # Push image to ECR 
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      # name - task definition of ECS Cluster
      - printf '[{"name":"Passwd-gen","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json