name: APP builder CI/CD

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
  
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    # Configuration AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # # Use spesific tags for docker images
    # - name: Docker meta tag
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     tags: |
    #       type=raw,value=action-{{date 'DD-MM-YYYY'}}-{{branch}}-{{sha}}

    # Login to ECR
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build docker image and push to ECR
    - name: Build docker image and push to AWS ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./App
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      